apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  labels:
    name: datastore-ing
  namespace: frontend
spec:
  ingressClassName: nginx
  rules:
    - host: ac4bceebccb7e484589afe558175745d-994904369.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: datastore-frontend-svc
                port:
                  number: 8081
