name: argocd_deploy

on:
  repository_dispatch:
    types: [argocd-deploy]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Trigger
        run: |
          echo "Triggered via repository_dispatch"
          echo "SHA: ${{ github.sha }}"

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      # ✅ Deploy ArgoCD Apps
      - name: Deploy Backend
        run: |
          kubectl apply -f argocd/backend/argocd-backend.yaml

      - name: Deploy Frontend
        run: |
          kubectl apply -f argocd/frotnend/argocd-frontend.yaml
          
      - name: Cleanup old ingress jobs
        run: |
          kubectl delete job ingress-nginx-admission-create -n ingress-nginx --ignore-not-found
          kubectl delete job ingress-nginx-admission-patch -n ingress-nginx --ignore-not-found

      # ✅ Install NGINX Ingress Controller (if not already)
      - name: Install NGINX Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml

      # ✅ Apply your app ingress
      - name: Apply App Ingress
        run: |
          kubectl apply -f netwroking/ingress.yaml

      # ✅ Check LoadBalancer Service
      - name: Get Ingress External IP
        run: |
          kubectl get svc -n ingress-nginx
